greetings:
  - Привет, ученичок!
  - Ну вот мы снова и увиделись...
  - Ну-с, продолжим наши занятия...
  - Шалом, шаломичк!

mistakes:
  - Ой-вей, не так...
  - Не-а, смотри как правильно

correct:
  - Нахон, верно же!
  - Отлично!
  - Молодчина, так держать!

another_word:
  - Попробуем-ка следующее слово —
  - Напиши вот что...
  - Как пишется вот это?
